# AutoGrad
autograd 包是 PyTorch 中所有神经网络的核心。autograd 软件包为 Tensors 上的所有操作提供自动微分。

## tensor梯度属性
- .requires_grad：tensor是否记录梯度的属性。默认为False；当设置为 True，则会开始跟踪针对 tensor 的所有操作，当调用 .backward() 时会将该张量的梯度累加到.grad里。
- .grad：tensor的梯度。调用 out.backward() 后，可以通过x.grad查看其梯度d(out)/d(x)。多次backward的梯度会累加，所以要在backward前将梯度置零。
- .grad_fn：保存着创建张量的 Function 的引用，如果用户自己创建张量，则grad_fn是None。

In [9]:
import torch

In [10]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.requires_grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True


In [11]:
y = x + 2
print(y)
print(y.requires_grad)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
True


In [12]:
z = y * y * 3
out = z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


## tensor梯度操作
- .backward()：自动计算所有有关tensor的梯度
- .detach()：停止 tensor 历史记录的跟踪
- with torch.no_grad(): 停止 tensor 历史记录的跟踪，停止使用内存
- .requires_grad_(True/False)：改变张量的 requires_grad 标记

In [13]:
print(x.grad)
out.backward() #out.backward()等同于out.backward(torch.tensor(1.))，如果out不是标量，也可以传向量进去计算梯度
print(x.grad)

None
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [15]:
x.requires_grad_(True)
print(x.requires_grad)
x.requires_grad_(False)
print(x.requires_grad)

True
False
