# Tensors
介绍pytorch tensor的创建、属性、操作。

In [1]:
import torch

## 创建tensor

In [3]:
#构造一个5x3矩阵，不初始化。
x = torch.empty(5, 3)
print(x)

tensor([[1.8217e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [4]:
#构造一个随机初始化的矩阵
x = torch.rand(5, 3)
print(x)

tensor([[0.6811, 0.1870, 0.9830],
        [0.4635, 0.4734, 0.3115],
        [0.8078, 0.9922, 0.3848],
        [0.5575, 0.6739, 0.0428],
        [0.6558, 0.5852, 0.2525]])


In [6]:
#构造一个矩阵全为 0，而且数据类型是 long.
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
#直接使用数据构造一个tensor
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
#直接使用已经存在的tensor构造一个tensor
x = x.new_ones(5, 3, dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.4215,  0.6465,  0.4875],
        [-1.2901, -1.4034, -0.8658],
        [-0.8445,  0.4405,  1.6135],
        [-0.9587,  0.6148,  0.9235],
        [-0.4390,  1.6723, -1.2301]])


## tensor的属性

In [18]:
# 获取tensor的维度信息
print(x.size())
print(x.size()[0])

torch.Size([4, 4])
4


In [19]:
# 获取单元素tensor的值
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.2679])
0.2678762376308441


## tensor的操作

### 加法

In [11]:
# 方法1
y = torch.rand(5,3)
z = x + y
print(z)

# 方法2
z = torch.add(x, y)
print(z)

# 方法3
z = torch.empty(5, 3)
torch.add(x, y, out=z)
print(z)

# 方法4
y.add_(x) #改变了y
print(y)

tensor([[ 0.6409,  1.3711,  1.0766],
        [-0.5459, -0.5844, -0.7473],
        [-0.6852,  0.9211,  2.1365],
        [-0.0299,  1.5463,  1.0052],
        [-0.1544,  2.4106, -0.7689]])
tensor([[ 0.6409,  1.3711,  1.0766],
        [-0.5459, -0.5844, -0.7473],
        [-0.6852,  0.9211,  2.1365],
        [-0.0299,  1.5463,  1.0052],
        [-0.1544,  2.4106, -0.7689]])
tensor([[ 0.6409,  1.3711,  1.0766],
        [-0.5459, -0.5844, -0.7473],
        [-0.6852,  0.9211,  2.1365],
        [-0.0299,  1.5463,  1.0052],
        [-0.1544,  2.4106, -0.7689]])
tensor([[ 0.6409,  1.3711,  1.0766],
        [-0.5459, -0.5844, -0.7473],
        [-0.6852,  0.9211,  2.1365],
        [-0.0299,  1.5463,  1.0052],
        [-0.1544,  2.4106, -0.7689]])


### 索引

In [12]:
# 可以使用标准的 NumPy 类似的索引操作
print(x[:, 1])

tensor([ 0.6465, -1.4034,  0.4405,  0.6148,  1.6723])


### reshape用view

In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
print(x)

tensor([[ 1.1200,  1.2088,  0.1454, -0.1616],
        [ 3.2046, -1.1155, -0.1401,  0.6121],
        [-1.7779,  0.3187, -2.5612, -1.8333],
        [ 1.2015,  0.4602,  0.0570,  0.8205]])


In [16]:
print(x[0, 0])

tensor(1.1200)


In [17]:
print(x[0][0].item())

1.1199657917022705
